name: Auto-Fix (non-blocking)

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  workflow_dispatch:

permissions:
  contents: write        # PRs from forks won't have this; script will detect and skip writes
  pull-requests: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v5
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: Run auto-fix
        id: run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scripts/auto-fix.mjs

      - name: Post advisory comment
        if: ${{ steps.run.outputs.advisory && steps.run.outputs.advisory != '' }}
        uses: actions/github-script@v7
        env:
          BODY: ${{ steps.run.outputs.advisory }}
        with:
          script: |
            const body = process.env.BODY;
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner, repo: context.repo.repo,
              issue_number: context.payload.pull_request.number, per_page: 50
            });
            const prev = comments.find(c => c.user?.type === 'Bot' && c.body?.startsWith('### 🤖 Auto-Fix advisory'));
            if (prev) await github.rest.issues.deleteComment({ owner: context.repo.owner, repo: context.repo.repo, comment_id: prev.id });
            await github.rest.issues.createComment({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.payload.pull_request.number, body });
