name: CI (lint, typecheck, test, build)

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix['node-version'] }}
          cache: npm

      - name: Install
        run: npm ci

      - name: Validate (lint + typecheck + tests + build)
        env:
          VITE_SANITY_PROJECT_ID: ${{ secrets.VITE_SANITY_PROJECT_ID }}
          VITE_SANITY_DATASET: ${{ secrets.VITE_SANITY_DATASET }}
        run: npm run ci:validate

      - name: Coverage (text + html)
        run: npm run test:coverage

