name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
    tags: ["v*"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: TypeScript Type Check
        run: npx tsc --noEmit

      - name: Code Formatting Check
        run: npm run format:check

      - name: Dependency Security Scan
        uses: actions/dependency-review-action@v4

      - name: Git Ignore Security Check
        run: |
          if ! grep -q ".env" .gitignore && ! grep -q "firebase.ts" .gitignore; then
            echo "Error: .gitignore is missing required entries for .env or firebase.ts"
            exit 1
          fi

      - name: Unused Dependency Check (Depcheck)
        if: >
          contains(github.event.head_commit.modified, 'package.json') ||
          contains(github.event.head_commit.modified, 'package-lock.json')
        run: npm run depcheck

      - name: Run linter
        run: npx npm run lint

      - name: Run tests
        run: npm run test || echo "No tests configured yet"

      - name: Build project
        run: npm run build

      - name: Broken Link Check
        uses: lycheeverse/lychee-action@v1
        with:
          args: "--verbose ./dist/index.html"

      - name: Upload build output
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
