name: E2E (Playwright)

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  e2e:
    if: ${{ hashFiles('tests/e2e/**/*.spec.ts') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: E2E tests
        run: npm run e2e

      - name: Upload Playwright report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

